const affirmations = [
    "Dziś jest dobry dzień, pełen możliwości i sukcesów.",
    "Moja praca ma wartość i znaczenie.",
    "Skupiam się na tym, co mogę zrobić najlepiej.",
    "Wnoszę pozytywną energię do mojego zespołu.",
    "Każde zadanie wykonuję z zaangażowaniem i uwagą.",
    "Pracuję efektywnie i spokojnie, bez zbędnego stresu.",
    "Dziś jestem produktywna/y i skoncentrowana/y.",
    "W pracy otaczają mnie pomocni i życzliwi ludzie.",
    "Ufam sobie i swoim umiejętnościom.",
    "Zasługuję na satysfakcję z pracy i dobre samopoczucie.",
    "Mam wszystko, czego potrzebuję, aby osiągnąć sukces.",
    "Codziennie rozwijam swoje umiejętności zawodowe.",
    "Wyzwania w pracy są dla mnie okazją do nauki.",
    "Skupiam się na rozwiązaniach, a nie na problemach.",
    "Każdego dnia staję się lepsza/y w tym, co robię.",
    "Moja praca przynosi wartość i jest doceniana.",
    "Mam kontrolę nad swoim czasem i priorytetami.",
    "Jestem kreatywna/y i potrafię znaleźć dobre rozwiązania.",
    "Moja energia i zaangażowanie inspirują innych.",
    "Pracuję mądrze, a nie ciężko.",
    "Współpraca z moimi kolegami i koleżankami jest owocna i przyjemna.",
    "Szanuję moich współpracowników i oni szanują mnie.",
    "Komunikuję się jasno i skutecznie.",
    "Moje relacje zawodowe są oparte na wzajemnym zaufaniu.",
    "Dzielę się wiedzą i pomagam innym.",
    "Ludzie wokół mnie wspierają mnie, a ja wspieram ich.",
    "Tworzę przyjazne i pozytywne środowisko pracy.",
    "Każdy w moim zespole wnosi coś wartościowego.",
    "Wiem, jak efektywnie współpracować z innymi.",
    "Potrafię słuchać i szanuję opinie innych.",
    "W pracy zachowuję spokój i kontrolę nad emocjami.",
    "Mam prawo do przerw i odpoczynku.",
    "Moje zdrowie psychiczne i fizyczne jest dla mnie ważne.",
    "Potrafię zarządzać stresem i napięciem.",
    "Każde wyzwanie traktuję jako okazję do nauki.",
    "Wiem, że nie wszystko musi być perfekcyjne.",
    "Ufam, że wszystko potoczy się tak, jak powinno.",
    "Odpuszczam to, na co nie mam wpływu.",
    "Jestem spokojna/y i zrównoważona/y nawet w trudnych sytuacjach.",
    "Moja praca nie definiuje mojej wartości jako człowieka.",
    "Działam zgodnie z moim planem i priorytetami.",
    "Pracuję mądrze i skutecznie zarządzam czasem.",
    "Skupiam się na jednym zadaniu na raz.",
    "Moja organizacja pracy pozwala mi osiągać świetne wyniki.",
    "Znajduję czas na to, co naprawdę ważne.",
    "Koncentruję się na zadaniach, które przynoszą najlepsze efekty.",
    "Wiem, kiedy powiedzieć 'nie' rzeczom, które mnie obciążają.",
    "Odpowiednio zarządzam swoją energią w ciągu dnia.",
    "Moja przestrzeń pracy sprzyja koncentracji i efektywności.",
    "Potrafię znaleźć równowagę między pracą a odpoczynkiem.",
    "Moje umiejętności są wartościowe i potrzebne.",
    "Jestem kompetentna/y i dobrze wykonuję swoją pracę.",
    "Zasługuję na uznanie i docenienie mojej pracy.",
    "Nie muszę być perfekcyjna/y - wystarczy, że daję z siebie to, co najlepsze.",
    "Moje pomysły są ważne i warte wysłuchania.",
    "Mam prawo do rozwoju i awansu zawodowego.",
    "Nie boję się podejmować nowych wyzwań.",
    "Moje osiągnięcia w pracy są powodem do dumy.",
    "Jestem wystarczająca/y dokładnie taka/i, jaka/i jestem.",
    "Mam wpływ na moje zawodowe sukcesy.",
    "Każdy dzień przybliża mnie do moich zawodowych celów.",
    "Rozwijam się i uczę nowych rzeczy.",
    "Jestem otwarta/y na nowe możliwości i wyzwania.",
    "Moja praca prowadzi mnie do sukcesu.",
    "Mam w sobie odwagę, by dążyć do awansu.",
    "Jestem gotowa/y na większą odpowiedzialność.",
    "Wiem, co chcę osiągnąć i konsekwentnie do tego dążę.",
    "Moja kariera rozwija się w najlepszym dla mnie kierunku.",
    "Przyciągam pozytywne zawodowe doświadczenia.",
    "Każde doświadczenie w pracy wzbogaca moje kompetencje.",
    "Praca może być przyjemna i satysfakcjonująca.",
    "Znajduję radość w tym, co robię.",
    "Doceniam każdą chwilę spędzoną w pracy.",
    "Uśmiecham się i tworzę przyjazną atmosferę wokół siebie.",
    "Potrafię cieszyć się nawet małymi sukcesami.",
    "Każdy dzień przynosi nowe, ciekawe wyzwania.",
    "Moje miejsce pracy jest przyjazne i inspirujące.",
    "Cieszę się, że mogę współpracować z fantastycznymi ludźmi.",
    "Moja praca pozwala mi spełniać się zawodowo.",
    "Mam kontrolę nad swoim szczęściem w pracy.",
    "Mam prawo do odpoczynku po pracy.",
    "Moja praca nie definiuje całego mojego życia.",
    "Poświęcam czas na to, co jest dla mnie ważne poza pracą.",
    "Wiem, jak znaleźć równowagę między obowiązkami a relaksem.",
    "Odpoczynek pomaga mi być jeszcze lepsza/y w pracy.",
    "Nie zabieram pracy do domu - zasługuję na czas dla siebie.",
    "Moje życie to więcej niż tylko obowiązki zawodowe.",
    "Mam prawo do relaksu bez wyrzutów sumienia.",
    "Moja efektywność wzrasta, gdy dbam o swój dobrostan.",
    "Życie zawodowe i prywatne mogą współistnieć w harmonii.",
  ];
  
  export default affirmations;